### ISSUE TITLE
Packaging on Nix

### ISSUE THREAD

**Issue by fufexan** [NLnetLabs/dnssec-ceremony-tools#5]
I'm trying to package the DNSSEC key signing suite for Nix as part of the Summer of Nix program, sponsored by NGI0.

While writing the Nix expressions, I had to patch the `oks.py` file as it wasn't working properly, and now I'm facing another issue
```
$ result/bin/oks.py
Traceback (most recent call last):
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
RuntimeError: Initialisation error (not initialized). Should never see this.
Exception ignored in: 'pkcs11._pkcs11.lib.__dealloc__'
Traceback (most recent call last):
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
RuntimeError: Initialisation error (not initialized). Should never see this.
Traceback (most recent call last):
  File "/home/mihai/Documents/code/son/dnssec-ceremony-tools/result/bin/oks.py", line 1744, in <module>
    result = main()
  File "/home/mihai/Documents/code/son/dnssec-ceremony-tools/result/bin/oks.py", line 1692, in main
    lib = pkcs11.lib(module)
  File "/nix/store/mc480csr0qb3s55xwj4v4qhv53sqj8pb-python3-3.9.6-env/lib/python3.9/site-packages/pkcs11/__init__.py", line 32, in lib
    _lib = _pkcs11.lib(so)
  File "pkcs11/_pkcs11.pyx", line 1432, in pkcs11._pkcs11.lib.__cinit__
  File "pkcs11/_errors.pyx", line 88, in pkcs11._pkcs11.assertRV
pkcs11.exceptions.GeneralError
```
Any idea how I can solve this?

The relevant fork where I've done the development is https://github.com/ngi-nix/dnssec-ceremony-tools/tree/flake.

**Comment by leenaars** [comment]
@fufexan: Have asked the developers, will get back to you when I get an answer.

**Comment by halderen** [comment]
Dear @fufexan @leenaars,

The runtime exception being thrown/shown is from the Python PKCS#11 layer that transfers the call to the software layer that handles the HSM.  Within one of the very first steps of the script it will try to load the shared library that implements the HSM or connects to the HSM.  This shared library should be an absolute file path as specified in the oks.conf configuration file.  Something went wrong while loading this file, which cascaded into a fatal error in the Python PKCS#11 layer (a deallocation of non-allocated memory I think).  There will be no error code from loading the PKCS#11 shared library available so there is no way do diagnose the error.  There are however a number of steps where further information /diagnostics can be made:
1. Verify that the right oks.conf configuration file is used (possibly by passing the -c parameter)
2. Verify the existance, availability and file permissions on the "module" parameter in the oks.conf configuration file
3. Verify that this shared library is loadable and complete (The command "ldd full-path-of-the-shared-library.so" should not give any "not found" or similar messages
4. Most PKCS#11 shared libraries (SoftHSM for sure) will log errors that occur whilst loading.  These messages should normally go into the syslog logging /var/log/messages, /var/log/syslog or similar.

Unfortunately the exception being thrown by the pkcs11/HSM library isn't of a proper type which I can handle gracefully and write out an error message, so little I can do about this.

Regarding the change on the fork, this seems to be dependent on the deployed environment, so I'll leave that in the fork for now.
